name: "manual workflow test"
on:
  workflow_dispatch
jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Say something
        run: echo "Hello?"